version: '{build}'

branches:
  only:
    - master
    - next

init:
  - git config --global core.autocrlf input

clone_folder: c:\dev\grantlee

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 12"
    QT5: C:\Qt\5.5\msvc2013
  - CMAKE_GENERATOR: "Visual Studio 12 Win64"
    QT5: C:\Qt\5.5\msvc2013_64

before_build:
- set Path=%QT5%\bin;%Path%

build:

build_script:
  - cd c:\dev\grantlee
  - md build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"
  - cmake --build . --config Debug
  - cmake --build . --config Release

# test_script:
#   - cmd: ctest --output-on-failure -C "Debug"
#   - cmd: ctest --output-on-failure -C "Release"
